// swift-tools-version:5.1
//===----------------------------------------------------------------------===//
//
// This source file is part of the AWSSDKSwift open source project
//
// Copyright (c) 2017-2020 the AWSSDKSwift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of AWSSDKSwift project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import PackageDescription

let package = Package(
    name: "aws-sdk-swift",
    platforms: [.iOS(.v12), .tvOS(.v12), .watchOS(.v5)],
    products: [
//        .library(name: "AWSACM", type:.dynamic,targets: ["AWSACM"]),
//        .library(name: "AWSACMPCA", type:.dynamic,targets: ["AWSACMPCA"]),
//        .library(name: "AWSAPIGateway", type:.dynamic,targets: ["AWSAPIGateway"]),
//        .library(name: "AWSAccessAnalyzer", type:.dynamic,targets: ["AWSAccessAnalyzer"]),
//        .library(name: "AWSAlexaForBusiness", type:.dynamic,targets: ["AWSAlexaForBusiness"]),
//        .library(name: "AWSAmplify", type:.dynamic,targets: ["AWSAmplify"]),
//        .library(name: "AWSApiGatewayManagementApi", type:.dynamic,targets: ["AWSApiGatewayManagementApi"]),
//        .library(name: "AWSApiGatewayV2", type:.dynamic,targets: ["AWSApiGatewayV2"]),
//        .library(name: "AWSAppConfig", type:.dynamic,targets: ["AWSAppConfig"]),
//        .library(name: "AWSAppMesh", type:.dynamic,targets: ["AWSAppMesh"]),
//        .library(name: "AWSAppStream", type:.dynamic,targets: ["AWSAppStream"]),
//        .library(name: "AWSAppSync", type:.dynamic,targets: ["AWSAppSync"]),
//        .library(name: "AWSApplicationAutoScaling", type:.dynamic,targets: ["AWSApplicationAutoScaling"]),
//        .library(name: "AWSApplicationDiscoveryService", type:.dynamic,targets: ["AWSApplicationDiscoveryService"]),
//        .library(name: "AWSApplicationInsights", type:.dynamic,targets: ["AWSApplicationInsights"]),
//        .library(name: "AWSAthena", type:.dynamic,targets: ["AWSAthena"]),
//        .library(name: "AWSAugmentedAIRuntime", type:.dynamic,targets: ["AWSAugmentedAIRuntime"]),
//        .library(name: "AWSAutoScaling", type:.dynamic,targets: ["AWSAutoScaling"]),
//        .library(name: "AWSAutoScalingPlans", type:.dynamic,targets: ["AWSAutoScalingPlans"]),
//        .library(name: "AWSBackup", type:.dynamic,targets: ["AWSBackup"]),
//        .library(name: "AWSBatch", type:.dynamic,targets: ["AWSBatch"]),
//        .library(name: "AWSBudgets", type:.dynamic,targets: ["AWSBudgets"]),
//        .library(name: "AWSChime", type:.dynamic,targets: ["AWSChime"]),
//        .library(name: "AWSCloud9", type:.dynamic,targets: ["AWSCloud9"]),
//        .library(name: "AWSCloudDirectory", type:.dynamic,targets: ["AWSCloudDirectory"]),
//        .library(name: "AWSCloudFormation", type:.dynamic,targets: ["AWSCloudFormation"]),
//        .library(name: "AWSCloudFront", type:.dynamic,targets: ["AWSCloudFront"]),
//        .library(name: "AWSCloudHSM", type:.dynamic,targets: ["AWSCloudHSM"]),
//        .library(name: "AWSCloudHSMV2", type:.dynamic,targets: ["AWSCloudHSMV2"]),
//        .library(name: "AWSCloudSearch", type:.dynamic,targets: ["AWSCloudSearch"]),
//        .library(name: "AWSCloudSearchDomain", type:.dynamic,targets: ["AWSCloudSearchDomain"]),
//        .library(name: "AWSCloudTrail", type:.dynamic,targets: ["AWSCloudTrail"]),
//        .library(name: "AWSCloudWatch", type:.dynamic,targets: ["AWSCloudWatch"]),
//        .library(name: "AWSCloudWatchEvents", type:.dynamic,targets: ["AWSCloudWatchEvents"]),
//        .library(name: "AWSCloudWatchLogs", type:.dynamic,targets: ["AWSCloudWatchLogs"]),
//        .library(name: "AWSCodeArtifact", type:.dynamic,targets: ["AWSCodeArtifact"]),
//        .library(name: "AWSCodeBuild", type:.dynamic,targets: ["AWSCodeBuild"]),
//        .library(name: "AWSCodeCommit", type:.dynamic,targets: ["AWSCodeCommit"]),
//        .library(name: "AWSCodeDeploy", type:.dynamic,targets: ["AWSCodeDeploy"]),
//        .library(name: "AWSCodeGuruProfiler", type:.dynamic,targets: ["AWSCodeGuruProfiler"]),
//        .library(name: "AWSCodeGuruReviewer", type:.dynamic,targets: ["AWSCodeGuruReviewer"]),
//        .library(name: "AWSCodePipeline", type:.dynamic,targets: ["AWSCodePipeline"]),
//        .library(name: "AWSCodeStar", type:.dynamic,targets: ["AWSCodeStar"]),
//        .library(name: "AWSCodeStarNotifications", type:.dynamic,targets: ["AWSCodeStarNotifications"]),
//        .library(name: "AWSCodeStarconnections", type:.dynamic,targets: ["AWSCodeStarconnections"]),
//        .library(name: "AWSCognitoIdentity", type:.dynamic,targets: ["AWSCognitoIdentity"]),
//        .library(name: "AWSCognitoIdentityProvider", type:.dynamic,targets: ["AWSCognitoIdentityProvider"]),
//        .library(name: "AWSCognitoSync", type:.dynamic,targets: ["AWSCognitoSync"]),
//        .library(name: "AWSComprehend", type:.dynamic,targets: ["AWSComprehend"]),
//        .library(name: "AWSComprehendMedical", type:.dynamic,targets: ["AWSComprehendMedical"]),
//        .library(name: "AWSComputeOptimizer", type:.dynamic,targets: ["AWSComputeOptimizer"]),
//        .library(name: "AWSConfigService", type:.dynamic,targets: ["AWSConfigService"]),
//        .library(name: "AWSConnect", type:.dynamic,targets: ["AWSConnect"]),
//        .library(name: "AWSConnectParticipant", type:.dynamic,targets: ["AWSConnectParticipant"]),
//        .library(name: "AWSCostExplorer", type:.dynamic,targets: ["AWSCostExplorer"]),
//        .library(name: "AWSCostandUsageReportService", type:.dynamic,targets: ["AWSCostandUsageReportService"]),
//        .library(name: "AWSDAX", type:.dynamic,targets: ["AWSDAX"]),
//        .library(name: "AWSDLM", type:.dynamic,targets: ["AWSDLM"]),
//        .library(name: "AWSDataExchange", type:.dynamic,targets: ["AWSDataExchange"]),
//        .library(name: "AWSDataPipeline", type:.dynamic,targets: ["AWSDataPipeline"]),
//        .library(name: "AWSDataSync", type:.dynamic,targets: ["AWSDataSync"]),
//        .library(name: "AWSDatabaseMigrationService", type:.dynamic,targets: ["AWSDatabaseMigrationService"]),
//        .library(name: "AWSDetective", type:.dynamic,targets: ["AWSDetective"]),
//        .library(name: "AWSDeviceFarm", type:.dynamic,targets: ["AWSDeviceFarm"]),
//        .library(name: "AWSDirectConnect", type:.dynamic,targets: ["AWSDirectConnect"]),
//        .library(name: "AWSDirectoryService", type:.dynamic,targets: ["AWSDirectoryService"]),
//        .library(name: "AWSDocDB", type:.dynamic,targets: ["AWSDocDB"]),
//        .library(name: "AWSDynamoDB", type:.dynamic,targets: ["AWSDynamoDB"]),
//        .library(name: "AWSDynamoDBStreams", type:.dynamic,targets: ["AWSDynamoDBStreams"]),
//        .library(name: "AWSEBS", type:.dynamic,targets: ["AWSEBS"]),
//        .library(name: "AWSEC2", type:.dynamic,targets: ["AWSEC2"]),
//        .library(name: "AWSEC2InstanceConnect", type:.dynamic,targets: ["AWSEC2InstanceConnect"]),
//        .library(name: "AWSECR", type:.dynamic,targets: ["AWSECR"]),
//        .library(name: "AWSECS", type:.dynamic,targets: ["AWSECS"]),
//        .library(name: "AWSEFS", type:.dynamic,targets: ["AWSEFS"]),
//        .library(name: "AWSEKS", type:.dynamic,targets: ["AWSEKS"]),
//        .library(name: "AWSELB", type:.dynamic,targets: ["AWSELB"]),
//        .library(name: "AWSELBV2", type:.dynamic,targets: ["AWSELBV2"]),
//        .library(name: "AWSEMR", type:.dynamic,targets: ["AWSEMR"]),
//        .library(name: "AWSElastiCache", type:.dynamic,targets: ["AWSElastiCache"]),
//        .library(name: "AWSElasticBeanstalk", type:.dynamic,targets: ["AWSElasticBeanstalk"]),
//        .library(name: "AWSElasticInference", type:.dynamic,targets: ["AWSElasticInference"]),
//        .library(name: "AWSElasticTranscoder", type:.dynamic,targets: ["AWSElasticTranscoder"]),
//        .library(name: "AWSElasticsearchService", type:.dynamic,targets: ["AWSElasticsearchService"]),
//        .library(name: "AWSEventBridge", type:.dynamic,targets: ["AWSEventBridge"]),
//        .library(name: "AWSFMS", type:.dynamic,targets: ["AWSFMS"]),
//        .library(name: "AWSFSx", type:.dynamic,targets: ["AWSFSx"]),
//        .library(name: "AWSFirehose", type:.dynamic,targets: ["AWSFirehose"]),
//        .library(name: "AWSForecastQueryService", type:.dynamic,targets: ["AWSForecastQueryService"]),
//        .library(name: "AWSForecastService", type:.dynamic,targets: ["AWSForecastService"]),
//        .library(name: "AWSFraudDetector", type:.dynamic,targets: ["AWSFraudDetector"]),
//        .library(name: "AWSGameLift", type:.dynamic,targets: ["AWSGameLift"]),
//        .library(name: "AWSGlacier", type:.dynamic,targets: ["AWSGlacier"]),
//        .library(name: "AWSGlobalAccelerator", type:.dynamic,targets: ["AWSGlobalAccelerator"]),
//        .library(name: "AWSGlue", type:.dynamic,targets: ["AWSGlue"]),
//        .library(name: "AWSGreengrass", type:.dynamic,targets: ["AWSGreengrass"]),
//        .library(name: "AWSGroundStation", type:.dynamic,targets: ["AWSGroundStation"]),
//        .library(name: "AWSGuardDuty", type:.dynamic,targets: ["AWSGuardDuty"]),
//        .library(name: "AWSHealth", type:.dynamic,targets: ["AWSHealth"]),
//        .library(name: "AWSHoneycode", type:.dynamic,targets: ["AWSHoneycode"]),
//        .library(name: "AWSIAM", type:.dynamic,targets: ["AWSIAM"]),
//        .library(name: "AWSImagebuilder", type:.dynamic,targets: ["AWSImagebuilder"]),
//        .library(name: "AWSImportExport", type:.dynamic,targets: ["AWSImportExport"]),
//        .library(name: "AWSInspector", type:.dynamic,targets: ["AWSInspector"]),
//        .library(name: "AWSIoT", type:.dynamic,targets: ["AWSIoT"]),
//        .library(name: "AWSIoT1ClickDevicesService", type:.dynamic,targets: ["AWSIoT1ClickDevicesService"]),
//        .library(name: "AWSIoT1ClickProjects", type:.dynamic,targets: ["AWSIoT1ClickProjects"]),
//        .library(name: "AWSIoTAnalytics", type:.dynamic,targets: ["AWSIoTAnalytics"]),
//        .library(name: "AWSIoTDataPlane", type:.dynamic,targets: ["AWSIoTDataPlane"]),
//        .library(name: "AWSIoTEvents", type:.dynamic,targets: ["AWSIoTEvents"]),
//        .library(name: "AWSIoTEventsData", type:.dynamic,targets: ["AWSIoTEventsData"]),
//        .library(name: "AWSIoTJobsDataPlane", type:.dynamic,targets: ["AWSIoTJobsDataPlane"]),
//        .library(name: "AWSIoTSecureTunneling", type:.dynamic,targets: ["AWSIoTSecureTunneling"]),
//        .library(name: "AWSIoTSiteWise", type:.dynamic,targets: ["AWSIoTSiteWise"]),
//        .library(name: "AWSIoTThingsGraph", type:.dynamic,targets: ["AWSIoTThingsGraph"]),
//        .library(name: "AWSKMS", type:.dynamic,targets: ["AWSKMS"]),
//        .library(name: "AWSKafka", type:.dynamic,targets: ["AWSKafka"]),
//        .library(name: "AWSKendra", type:.dynamic,targets: ["AWSKendra"]),
//        .library(name: "AWSKinesis", type:.dynamic,targets: ["AWSKinesis"]),
//        .library(name: "AWSKinesisAnalytics", type:.dynamic,targets: ["AWSKinesisAnalytics"]),
//        .library(name: "AWSKinesisAnalyticsV2", type:.dynamic,targets: ["AWSKinesisAnalyticsV2"]),
//        .library(name: "AWSKinesisVideo", type:.dynamic,targets: ["AWSKinesisVideo"]),
//        .library(name: "AWSKinesisVideoArchivedMedia", type:.dynamic,targets: ["AWSKinesisVideoArchivedMedia"]),
//        .library(name: "AWSKinesisVideoMedia", type:.dynamic,targets: ["AWSKinesisVideoMedia"]),
//        .library(name: "AWSKinesisVideoSignalingChannels", type:.dynamic,targets: ["AWSKinesisVideoSignalingChannels"]),
//        .library(name: "AWSLakeFormation", type:.dynamic,targets: ["AWSLakeFormation"]),
        .library(name: "AWSLambda", type:.dynamic,targets: ["AWSLambda"]),
//        .library(name: "AWSLexModelBuildingService", type:.dynamic,targets: ["AWSLexModelBuildingService"]),
//        .library(name: "AWSLexRuntimeService", type:.dynamic,targets: ["AWSLexRuntimeService"]),
//        .library(name: "AWSLicenseManager", type:.dynamic,targets: ["AWSLicenseManager"]),
//        .library(name: "AWSLightsail", type:.dynamic,targets: ["AWSLightsail"]),
//        .library(name: "AWSMQ", type:.dynamic,targets: ["AWSMQ"]),
//        .library(name: "AWSMTurk", type:.dynamic,targets: ["AWSMTurk"]),
//        .library(name: "AWSMachineLearning", type:.dynamic,targets: ["AWSMachineLearning"]),
//        .library(name: "AWSMacie", type:.dynamic,targets: ["AWSMacie"]),
//        .library(name: "AWSMacie2", type:.dynamic,targets: ["AWSMacie2"]),
//        .library(name: "AWSManagedBlockchain", type:.dynamic,targets: ["AWSManagedBlockchain"]),
//        .library(name: "AWSMarketplaceCatalog", type:.dynamic,targets: ["AWSMarketplaceCatalog"]),
//        .library(name: "AWSMarketplaceCommerceAnalytics", type:.dynamic,targets: ["AWSMarketplaceCommerceAnalytics"]),
//        .library(name: "AWSMarketplaceEntitlementService", type:.dynamic,targets: ["AWSMarketplaceEntitlementService"]),
//        .library(name: "AWSMarketplaceMetering", type:.dynamic,targets: ["AWSMarketplaceMetering"]),
//        .library(name: "AWSMediaConnect", type:.dynamic,targets: ["AWSMediaConnect"]),
//        .library(name: "AWSMediaConvert", type:.dynamic,targets: ["AWSMediaConvert"]),
//        .library(name: "AWSMediaLive", type:.dynamic,targets: ["AWSMediaLive"]),
//        .library(name: "AWSMediaPackage", type:.dynamic,targets: ["AWSMediaPackage"]),
//        .library(name: "AWSMediaPackageVod", type:.dynamic,targets: ["AWSMediaPackageVod"]),
//        .library(name: "AWSMediaStore", type:.dynamic,targets: ["AWSMediaStore"]),
//        .library(name: "AWSMediaStoreData", type:.dynamic,targets: ["AWSMediaStoreData"]),
//        .library(name: "AWSMediaTailor", type:.dynamic,targets: ["AWSMediaTailor"]),
//        .library(name: "AWSMigrationHub", type:.dynamic,targets: ["AWSMigrationHub"]),
//        .library(name: "AWSMigrationHubConfig", type:.dynamic,targets: ["AWSMigrationHubConfig"]),
//        .library(name: "AWSMobile", type:.dynamic,targets: ["AWSMobile"]),
//        .library(name: "AWSMobileAnalytics", type:.dynamic,targets: ["AWSMobileAnalytics"]),
//        .library(name: "AWSNeptune", type:.dynamic,targets: ["AWSNeptune"]),
//        .library(name: "AWSNetworkManager", type:.dynamic,targets: ["AWSNetworkManager"]),
//        .library(name: "AWSOpsWorks", type:.dynamic,targets: ["AWSOpsWorks"]),
//        .library(name: "AWSOpsWorksCM", type:.dynamic,targets: ["AWSOpsWorksCM"]),
//        .library(name: "AWSOrganizations", type:.dynamic,targets: ["AWSOrganizations"]),
//        .library(name: "AWSOutposts", type:.dynamic,targets: ["AWSOutposts"]),
//        .library(name: "AWSPI", type:.dynamic,targets: ["AWSPI"]),
//        .library(name: "AWSPersonalize", type:.dynamic,targets: ["AWSPersonalize"]),
//        .library(name: "AWSPersonalizeEvents", type:.dynamic,targets: ["AWSPersonalizeEvents"]),
//        .library(name: "AWSPersonalizeRuntime", type:.dynamic,targets: ["AWSPersonalizeRuntime"]),
//        .library(name: "AWSPinpoint", type:.dynamic,targets: ["AWSPinpoint"]),
//        .library(name: "AWSPinpointEmail", type:.dynamic,targets: ["AWSPinpointEmail"]),
//        .library(name: "AWSPinpointSMSVoice", type:.dynamic,targets: ["AWSPinpointSMSVoice"]),
//        .library(name: "AWSPolly", type:.dynamic,targets: ["AWSPolly"]),
//        .library(name: "AWSPricing", type:.dynamic,targets: ["AWSPricing"]),
//        .library(name: "AWSQLDB", type:.dynamic,targets: ["AWSQLDB"]),
//        .library(name: "AWSQLDBSession", type:.dynamic,targets: ["AWSQLDBSession"]),
//        .library(name: "AWSQuickSight", type:.dynamic,targets: ["AWSQuickSight"]),
//        .library(name: "AWSRAM", type:.dynamic,targets: ["AWSRAM"]),
//        .library(name: "AWSRDS", type:.dynamic,targets: ["AWSRDS"]),
//        .library(name: "AWSRDSDataService", type:.dynamic,targets: ["AWSRDSDataService"]),
//        .library(name: "AWSRedshift", type:.dynamic,targets: ["AWSRedshift"]),
//        .library(name: "AWSRekognition", type:.dynamic,targets: ["AWSRekognition"]),
//        .library(name: "AWSResourceGroups", type:.dynamic,targets: ["AWSResourceGroups"]),
//        .library(name: "AWSResourceGroupsTaggingAPI", type:.dynamic,targets: ["AWSResourceGroupsTaggingAPI"]),
//        .library(name: "AWSRoboMaker", type:.dynamic,targets: ["AWSRoboMaker"]),
//        .library(name: "AWSRoute53", type:.dynamic,targets: ["AWSRoute53"]),
//        .library(name: "AWSRoute53Domains", type:.dynamic,targets: ["AWSRoute53Domains"]),
//        .library(name: "AWSRoute53Resolver", type:.dynamic,targets: ["AWSRoute53Resolver"]),
        .library(name: "AWSS3", type:.dynamic,targets: ["AWSS3"]),
//        .library(name: "AWSS3Control", type:.dynamic,targets: ["AWSS3Control"]),
//        .library(name: "AWSSES", type:.dynamic,targets: ["AWSSES"]),
//        .library(name: "AWSSESV2", type:.dynamic,targets: ["AWSSESV2"]),
//        .library(name: "AWSSFN", type:.dynamic,targets: ["AWSSFN"]),
//        .library(name: "AWSSMS", type:.dynamic,targets: ["AWSSMS"]),
//        .library(name: "AWSSNS", type:.dynamic,targets: ["AWSSNS"]),
//        .library(name: "AWSSQS", type:.dynamic,targets: ["AWSSQS"]),
//        .library(name: "AWSSSM", type:.dynamic,targets: ["AWSSSM"]),
//        .library(name: "AWSSSO", type:.dynamic,targets: ["AWSSSO"]),
//        .library(name: "AWSSSOOIDC", type:.dynamic,targets: ["AWSSSOOIDC"]),
//        .library(name: "AWSSTS", type:.dynamic,targets: ["AWSSTS"]),
//        .library(name: "AWSSWF", type:.dynamic,targets: ["AWSSWF"]),
//        .library(name: "AWSSageMaker", type:.dynamic,targets: ["AWSSageMaker"]),
//        .library(name: "AWSSageMakerRuntime", type:.dynamic,targets: ["AWSSageMakerRuntime"]),
//        .library(name: "AWSSavingsPlans", type:.dynamic,targets: ["AWSSavingsPlans"]),
//        .library(name: "AWSSchemas", type:.dynamic,targets: ["AWSSchemas"]),
//        .library(name: "AWSSecretsManager", type:.dynamic,targets: ["AWSSecretsManager"]),
//        .library(name: "AWSSecurityHub", type:.dynamic,targets: ["AWSSecurityHub"]),
//        .library(name: "AWSServerlessApplicationRepository", type:.dynamic,targets: ["AWSServerlessApplicationRepository"]),
//        .library(name: "AWSServiceCatalog", type:.dynamic,targets: ["AWSServiceCatalog"]),
//        .library(name: "AWSServiceDiscovery", type:.dynamic,targets: ["AWSServiceDiscovery"]),
//        .library(name: "AWSServiceQuotas", type:.dynamic,targets: ["AWSServiceQuotas"]),
//        .library(name: "AWSShield", type:.dynamic,targets: ["AWSShield"]),
//        .library(name: "AWSSigner", type:.dynamic,targets: ["AWSSigner"]),
//        .library(name: "AWSSimpleDB", type:.dynamic,targets: ["AWSSimpleDB"]),
//        .library(name: "AWSSnowball", type:.dynamic,targets: ["AWSSnowball"]),
//        .library(name: "AWSStorageGateway", type:.dynamic,targets: ["AWSStorageGateway"]),
//        .library(name: "AWSSupport", type:.dynamic,targets: ["AWSSupport"]),
//        .library(name: "AWSSynthetics", type:.dynamic,targets: ["AWSSynthetics"]),
//        .library(name: "AWSTextract", type:.dynamic,targets: ["AWSTextract"]),
//        .library(name: "AWSTranscribeService", type:.dynamic,targets: ["AWSTranscribeService"]),
//        .library(name: "AWSTranscribeStreamingService", type:.dynamic,targets: ["AWSTranscribeStreamingService"]),
//        .library(name: "AWSTransfer", type:.dynamic,targets: ["AWSTransfer"]),
//        .library(name: "AWSTranslate", type:.dynamic,targets: ["AWSTranslate"]),
//        .library(name: "AWSWAF", type:.dynamic,targets: ["AWSWAF"]),
//        .library(name: "AWSWAFRegional", type:.dynamic,targets: ["AWSWAFRegional"]),
//        .library(name: "AWSWAFV2", type:.dynamic,targets: ["AWSWAFV2"]),
//        .library(name: "AWSWorkDocs", type:.dynamic,targets: ["AWSWorkDocs"]),
//        .library(name: "AWSWorkLink", type:.dynamic,targets: ["AWSWorkLink"]),
//        .library(name: "AWSWorkMail", type:.dynamic,targets: ["AWSWorkMail"]),
//        .library(name: "AWSWorkMailMessageFlow", type:.dynamic,targets: ["AWSWorkMailMessageFlow"]),
//        .library(name: "AWSWorkSpaces", type:.dynamic,targets: ["AWSWorkSpaces"]),
//        .library(name: "AWSXRay", type:.dynamic,targets: ["AWSXRay"]),
    ],
    dependencies: [
        .package(url: "https://github.com/brightenai/aws-sdk-swift-core.git", .branch("master")),
    ],
    targets: [
//        .target(name: "AWSACM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ACM"),
//        .target(name: "AWSACMPCA", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ACMPCA"),
//        .target(name: "AWSAPIGateway", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/APIGateway", "Extensions/APIGateway"]),
//        .target(name: "AWSAccessAnalyzer", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AccessAnalyzer"),
//        .target(name: "AWSAlexaForBusiness", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AlexaForBusiness"),
//        .target(name: "AWSAmplify", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Amplify"),
//        .target(name: "AWSApiGatewayManagementApi", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ApiGatewayManagementApi"),
//        .target(name: "AWSApiGatewayV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ApiGatewayV2"),
//        .target(name: "AWSAppConfig", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AppConfig"),
//        .target(name: "AWSAppMesh", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AppMesh"),
//        .target(name: "AWSAppStream", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AppStream"),
//        .target(name: "AWSAppSync", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AppSync"),
//        .target(name: "AWSApplicationAutoScaling", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ApplicationAutoScaling"),
//        .target(name: "AWSApplicationDiscoveryService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ApplicationDiscoveryService"),
//        .target(name: "AWSApplicationInsights", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ApplicationInsights"),
//        .target(name: "AWSAthena", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Athena"),
//        .target(name: "AWSAugmentedAIRuntime", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AugmentedAIRuntime"),
//        .target(name: "AWSAutoScaling", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AutoScaling"),
//        .target(name: "AWSAutoScalingPlans", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/AutoScalingPlans"),
//        .target(name: "AWSBackup", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Backup"),
//        .target(name: "AWSBatch", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Batch"),
//        .target(name: "AWSBudgets", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Budgets"),
//        .target(name: "AWSChime", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Chime"),
//        .target(name: "AWSCloud9", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Cloud9"),
//        .target(name: "AWSCloudDirectory", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudDirectory"),
//        .target(name: "AWSCloudFormation", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudFormation"),
//        .target(name: "AWSCloudFront", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudFront"),
//        .target(name: "AWSCloudHSM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudHSM"),
//        .target(name: "AWSCloudHSMV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudHSMV2"),
//        .target(name: "AWSCloudSearch", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudSearch"),
//        .target(name: "AWSCloudSearchDomain", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudSearchDomain"),
//        .target(name: "AWSCloudTrail", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudTrail"),
//        .target(name: "AWSCloudWatch", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudWatch"),
//        .target(name: "AWSCloudWatchEvents", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudWatchEvents"),
//        .target(name: "AWSCloudWatchLogs", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CloudWatchLogs"),
//        .target(name: "AWSCodeArtifact", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeArtifact"),
//        .target(name: "AWSCodeBuild", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeBuild"),
//        .target(name: "AWSCodeCommit", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeCommit"),
//        .target(name: "AWSCodeDeploy", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeDeploy"),
//        .target(name: "AWSCodeGuruProfiler", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeGuruProfiler"),
//        .target(name: "AWSCodeGuruReviewer", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeGuruReviewer"),
//        .target(name: "AWSCodePipeline", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodePipeline"),
//        .target(name: "AWSCodeStar", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeStar"),
//        .target(name: "AWSCodeStarNotifications", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeStarNotifications"),
//        .target(name: "AWSCodeStarconnections", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CodeStarconnections"),
//        .target(name: "AWSCognitoIdentity", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/CognitoIdentity", "Extensions/CognitoIdentity"]),
//        .target(name: "AWSCognitoIdentityProvider", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CognitoIdentityProvider"),
//        .target(name: "AWSCognitoSync", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CognitoSync"),
//        .target(name: "AWSComprehend", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Comprehend"),
//        .target(name: "AWSComprehendMedical", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ComprehendMedical"),
//        .target(name: "AWSComputeOptimizer", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ComputeOptimizer"),
//        .target(name: "AWSConfigService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ConfigService"),
//        .target(name: "AWSConnect", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Connect"),
//        .target(name: "AWSConnectParticipant", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ConnectParticipant"),
//        .target(name: "AWSCostExplorer", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CostExplorer"),
//        .target(name: "AWSCostandUsageReportService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/CostandUsageReportService"),
//        .target(name: "AWSDAX", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DAX"),
//        .target(name: "AWSDLM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DLM"),
//        .target(name: "AWSDataExchange", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DataExchange"),
//        .target(name: "AWSDataPipeline", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DataPipeline"),
//        .target(name: "AWSDataSync", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DataSync"),
//        .target(name: "AWSDatabaseMigrationService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DatabaseMigrationService"),
//        .target(name: "AWSDetective", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Detective"),
//        .target(name: "AWSDeviceFarm", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DeviceFarm"),
//        .target(name: "AWSDirectConnect", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DirectConnect"),
//        .target(name: "AWSDirectoryService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DirectoryService"),
//        .target(name: "AWSDocDB", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DocDB"),
//        .target(name: "AWSDynamoDB", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/DynamoDB", "Extensions/DynamoDB"]),
//        .target(name: "AWSDynamoDBStreams", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/DynamoDBStreams"),
//        .target(name: "AWSEBS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EBS"),
//        .target(name: "AWSEC2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/EC2", "Extensions/EC2"]),
//        .target(name: "AWSEC2InstanceConnect", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EC2InstanceConnect"),
//        .target(name: "AWSECR", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ECR"),
//        .target(name: "AWSECS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ECS"),
//        .target(name: "AWSEFS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EFS"),
//        .target(name: "AWSEKS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EKS"),
//        .target(name: "AWSELB", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ELB"),
//        .target(name: "AWSELBV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ELBV2"),
//        .target(name: "AWSEMR", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EMR"),
//        .target(name: "AWSElastiCache", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ElastiCache"),
//        .target(name: "AWSElasticBeanstalk", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ElasticBeanstalk"),
//        .target(name: "AWSElasticInference", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ElasticInference"),
//        .target(name: "AWSElasticTranscoder", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ElasticTranscoder"),
//        .target(name: "AWSElasticsearchService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ElasticsearchService"),
//        .target(name: "AWSEventBridge", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/EventBridge"),
//        .target(name: "AWSFMS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/FMS"),
//        .target(name: "AWSFSx", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/FSx"),
//        .target(name: "AWSFirehose", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Firehose"),
//        .target(name: "AWSForecastQueryService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ForecastQueryService"),
//        .target(name: "AWSForecastService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ForecastService"),
//        .target(name: "AWSFraudDetector", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/FraudDetector"),
//        .target(name: "AWSGameLift", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/GameLift"),
//        .target(name: "AWSGlacier", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/Glacier", "Extensions/Glacier"]),
//        .target(name: "AWSGlobalAccelerator", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/GlobalAccelerator"),
//        .target(name: "AWSGlue", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Glue"),
//        .target(name: "AWSGreengrass", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Greengrass"),
//        .target(name: "AWSGroundStation", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/GroundStation"),
//        .target(name: "AWSGuardDuty", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/GuardDuty"),
//        .target(name: "AWSHealth", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Health"),
//        .target(name: "AWSHoneycode", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Honeycode"),
//        .target(name: "AWSIAM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IAM"),
//        .target(name: "AWSImagebuilder", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Imagebuilder"),
//        .target(name: "AWSImportExport", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ImportExport"),
//        .target(name: "AWSInspector", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Inspector"),
//        .target(name: "AWSIoT", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoT"),
//        .target(name: "AWSIoT1ClickDevicesService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoT1ClickDevicesService"),
//        .target(name: "AWSIoT1ClickProjects", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoT1ClickProjects"),
//        .target(name: "AWSIoTAnalytics", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTAnalytics"),
//        .target(name: "AWSIoTDataPlane", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTDataPlane"),
//        .target(name: "AWSIoTEvents", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTEvents"),
//        .target(name: "AWSIoTEventsData", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTEventsData"),
//        .target(name: "AWSIoTJobsDataPlane", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTJobsDataPlane"),
//        .target(name: "AWSIoTSecureTunneling", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTSecureTunneling"),
//        .target(name: "AWSIoTSiteWise", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTSiteWise"),
//        .target(name: "AWSIoTThingsGraph", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/IoTThingsGraph"),
//        .target(name: "AWSKMS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KMS"),
//        .target(name: "AWSKafka", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Kafka"),
//        .target(name: "AWSKendra", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Kendra"),
//        .target(name: "AWSKinesis", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Kinesis"),
//        .target(name: "AWSKinesisAnalytics", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisAnalytics"),
//        .target(name: "AWSKinesisAnalyticsV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisAnalyticsV2"),
//        .target(name: "AWSKinesisVideo", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisVideo"),
//        .target(name: "AWSKinesisVideoArchivedMedia", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisVideoArchivedMedia"),
//        .target(name: "AWSKinesisVideoMedia", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisVideoMedia"),
//        .target(name: "AWSKinesisVideoSignalingChannels", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/KinesisVideoSignalingChannels"),
//        .target(name: "AWSLakeFormation", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/LakeFormation"),
        .target(name: "AWSLambda", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Lambda"),
//        .target(name: "AWSLexModelBuildingService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/LexModelBuildingService"),
//        .target(name: "AWSLexRuntimeService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/LexRuntimeService"),
//        .target(name: "AWSLicenseManager", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/LicenseManager"),
//        .target(name: "AWSLightsail", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Lightsail"),
//        .target(name: "AWSMQ", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MQ"),
//        .target(name: "AWSMTurk", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MTurk"),
//        .target(name: "AWSMachineLearning", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MachineLearning"),
//        .target(name: "AWSMacie", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Macie"),
//        .target(name: "AWSMacie2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Macie2"),
//        .target(name: "AWSManagedBlockchain", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ManagedBlockchain"),
//        .target(name: "AWSMarketplaceCatalog", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MarketplaceCatalog"),
//        .target(name: "AWSMarketplaceCommerceAnalytics", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MarketplaceCommerceAnalytics"),
//        .target(name: "AWSMarketplaceEntitlementService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MarketplaceEntitlementService"),
//        .target(name: "AWSMarketplaceMetering", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MarketplaceMetering"),
//        .target(name: "AWSMediaConnect", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaConnect"),
//        .target(name: "AWSMediaConvert", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaConvert"),
//        .target(name: "AWSMediaLive", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaLive"),
//        .target(name: "AWSMediaPackage", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaPackage"),
//        .target(name: "AWSMediaPackageVod", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaPackageVod"),
//        .target(name: "AWSMediaStore", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaStore"),
//        .target(name: "AWSMediaStoreData", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaStoreData"),
//        .target(name: "AWSMediaTailor", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MediaTailor"),
//        .target(name: "AWSMigrationHub", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MigrationHub"),
//        .target(name: "AWSMigrationHubConfig", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MigrationHubConfig"),
//        .target(name: "AWSMobile", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Mobile"),
//        .target(name: "AWSMobileAnalytics", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/MobileAnalytics"),
//        .target(name: "AWSNeptune", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Neptune"),
//        .target(name: "AWSNetworkManager", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/NetworkManager"),
//        .target(name: "AWSOpsWorks", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/OpsWorks"),
//        .target(name: "AWSOpsWorksCM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/OpsWorksCM"),
//        .target(name: "AWSOrganizations", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Organizations"),
//        .target(name: "AWSOutposts", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Outposts"),
//        .target(name: "AWSPI", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/PI"),
//        .target(name: "AWSPersonalize", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Personalize"),
//        .target(name: "AWSPersonalizeEvents", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/PersonalizeEvents"),
//        .target(name: "AWSPersonalizeRuntime", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/PersonalizeRuntime"),
//        .target(name: "AWSPinpoint", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Pinpoint"),
//        .target(name: "AWSPinpointEmail", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/PinpointEmail"),
//        .target(name: "AWSPinpointSMSVoice", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/PinpointSMSVoice"),
//        .target(name: "AWSPolly", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Polly"),
//        .target(name: "AWSPricing", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Pricing"),
//        .target(name: "AWSQLDB", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/QLDB"),
//        .target(name: "AWSQLDBSession", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/QLDBSession"),
//        .target(name: "AWSQuickSight", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/QuickSight"),
//        .target(name: "AWSRAM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/RAM"),
//        .target(name: "AWSRDS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/RDS"),
//        .target(name: "AWSRDSDataService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/RDSDataService"),
//        .target(name: "AWSRedshift", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Redshift"),
//        .target(name: "AWSRekognition", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Rekognition"),
//        .target(name: "AWSResourceGroups", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ResourceGroups"),
//        .target(name: "AWSResourceGroupsTaggingAPI", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ResourceGroupsTaggingAPI"),
//        .target(name: "AWSRoboMaker", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/RoboMaker"),
//        .target(name: "AWSRoute53", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Route53"),
//        .target(name: "AWSRoute53Domains", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Route53Domains"),
//        .target(name: "AWSRoute53Resolver", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Route53Resolver"),
        .target(name: "AWSS3", dependencies: ["AWSSDKSwiftCore", "CAWSZlib"], path: "./Sources/AWSSDKSwift/", sources: ["Services/S3", "Extensions/S3"]),
//        .target(name: "AWSS3Control", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/S3Control", "Extensions/S3Control"]),
//        .target(name: "AWSSES", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SES"),
//        .target(name: "AWSSESV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SESV2"),
//        .target(name: "AWSSFN", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SFN"),
//        .target(name: "AWSSMS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SMS"),
//        .target(name: "AWSSNS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SNS"),
//        .target(name: "AWSSQS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SQS"),
//        .target(name: "AWSSSM", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SSM"),
//        .target(name: "AWSSSO", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SSO"),
//        .target(name: "AWSSSOOIDC", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SSOOIDC"),
//        .target(name: "AWSSTS", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/", sources: ["Services/STS", "Extensions/STS"]),
//        .target(name: "AWSSWF", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SWF"),
//        .target(name: "AWSSageMaker", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SageMaker"),
//        .target(name: "AWSSageMakerRuntime", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SageMakerRuntime"),
//        .target(name: "AWSSavingsPlans", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SavingsPlans"),
//        .target(name: "AWSSchemas", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Schemas"),
//        .target(name: "AWSSecretsManager", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SecretsManager"),
//        .target(name: "AWSSecurityHub", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SecurityHub"),
//        .target(name: "AWSServerlessApplicationRepository", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ServerlessApplicationRepository"),
//        .target(name: "AWSServiceCatalog", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ServiceCatalog"),
//        .target(name: "AWSServiceDiscovery", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ServiceDiscovery"),
//        .target(name: "AWSServiceQuotas", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/ServiceQuotas"),
//        .target(name: "AWSShield", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Shield"),
//        .target(name: "AWSSigner", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Signer"),
//        .target(name: "AWSSimpleDB", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/SimpleDB"),
//        .target(name: "AWSSnowball", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Snowball"),
//        .target(name: "AWSStorageGateway", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/StorageGateway"),
//        .target(name: "AWSSupport", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Support"),
//        .target(name: "AWSSynthetics", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Synthetics"),
//        .target(name: "AWSTextract", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Textract"),
//        .target(name: "AWSTranscribeService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/TranscribeService"),
//        .target(name: "AWSTranscribeStreamingService", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/TranscribeStreamingService"),
//        .target(name: "AWSTransfer", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Transfer"),
//        .target(name: "AWSTranslate", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/Translate"),
//        .target(name: "AWSWAF", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WAF"),
//        .target(name: "AWSWAFRegional", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WAFRegional"),
//        .target(name: "AWSWAFV2", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WAFV2"),
//        .target(name: "AWSWorkDocs", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WorkDocs"),
//        .target(name: "AWSWorkLink", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WorkLink"),
//        .target(name: "AWSWorkMail", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WorkMail"),
//        .target(name: "AWSWorkMailMessageFlow", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WorkMailMessageFlow"),
//        .target(name: "AWSWorkSpaces", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/WorkSpaces"),
//        .target(name: "AWSXRay", dependencies: ["AWSSDKSwiftCore"], path: "./Sources/AWSSDKSwift/Services/XRay"),
        .target(name: "CAWSZlib", linkerSettings: [.linkedLibrary("z")]),

//        .testTarget(name: "AWSSDKSwiftTests", dependencies: [
//            "AWSACM",
//            "AWSAPIGateway",
//            "AWSCloudFront",
//            "AWSDynamoDB",
//            "AWSEC2",
//            "AWSGlacier",
//            "AWSIAM",
//            "AWSRoute53",
//            "AWSS3",
//            "AWSSES",
//            "AWSSNS",
//            "AWSSQS",
//            "AWSSSM",
//            "AWSSTS",
//        ]),
    ]
)
